//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wheatech.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wheatech.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is ambiguous: it could come from assembly &apos;{1}&apos; or from assembly &apos;{2}&apos;. Please specify the assembly explicitly in the type name. 的本地化字符串。
        /// </summary>
        internal static string Ambiguous_type {
            get {
                return ResourceManager.GetString("Ambiguous_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &quot;{0}&quot; is not of type &quot;{1}&quot; and cannot be used in this generic collection. 的本地化字符串。
        /// </summary>
        internal static string Arg_WrongType {
            get {
                return ResourceManager.GetString("Arg_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or an empty string. 的本地化字符串。
        /// </summary>
        internal static string Argument_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is not an enumeration. 的本地化字符串。
        /// </summary>
        internal static string Argument_MustBeEnum {
            get {
                return ResourceManager.GetString("Argument_MustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index was out of range. Must be non-negative and less than the size of the collection. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be non-negative. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The assembly string format is invalid: {0}. 的本地化字符串。
        /// </summary>
        internal static string AssemblyString_InvalidFormat {
            get {
                return ResourceManager.GetString("AssemblyString_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field value &apos;{0}&apos; cannot be converted to {1} for the component property &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Cannot_Convert_Field {
            get {
                return ResourceManager.GetString("Cannot_Convert_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert from &apos;{0}&apos; to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Cannot_Convert_Type {
            get {
                return ResourceManager.GetString("Cannot_Convert_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert value &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Cannot_Convert_Value {
            get {
                return ResourceManager.GetString("Cannot_Convert_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find the type &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Cannot_Find_Type {
            get {
                return ResourceManager.GetString("Cannot_Find_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data uri cannot be empty string. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Cannot_Be_Empty {
            get {
                return ResourceManager.GetString("DataUri_Cannot_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data uri cannot be null. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Cannot_Be_Null {
            get {
                return ResourceManager.GetString("DataUri_Cannot_Be_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content of data uri cannot be null. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Content_Cannot_Be_Null {
            get {
                return ResourceManager.GetString("DataUri_Content_Cannot_Be_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content of data uri cannot be null or an empty string. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Content_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("DataUri_Content_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized data uri format. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Invalid_Format {
            get {
                return ResourceManager.GetString("DataUri_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized data uri for invalid media type: {0}. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Invalid_MediaType {
            get {
                return ResourceManager.GetString("DataUri_Invalid_MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized data uri for unknown data encoding: {0}. 的本地化字符串。
        /// </summary>
        internal static string DataUri_Unknown_Encoding {
            get {
                return ResourceManager.GetString("DataUri_Unknown_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a valid version string. 的本地化字符串。
        /// </summary>
        internal static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
    }
}
